### ISSUE TITLE
Extracted videos don't show up in browser interface

### ISSUE THREAD

**Issue by drasmuss** [jldowns/vatic-docker#2]
This is on the `visionfork` branch (I tried but couldn't manage to adapt the instructions from `master` to run on Windows).

So I run `docker run -it -p 8111:80 -v $PWD/data:/root/vatic/data npsvisionlab/vatic-docker /bin/bash -C /root/vatic/example.sh`

The extraction script runs successfully, and if I look at the `frames_in` folder I can see all the frames from the video.  But when I go to `http://localhost:8111/directory/` and load one of the video segments for annotation, it's from a completely different video (one I was working on earlier).  Any idea what might be causing this?

**Comment by jldowns** [comment]
Hey, I ran into a similar problem yesterday. My problem was that my browser was caching the images instead of downloading new ones. What happens if you switch browsers or clear your cache? I'm using Chrome's incognito mode to prevent caching as a temporary fix.

In the long term I think it's a problem with the server configuration. I haven't confirmed it but I suspect apache is returning a 304-Not modified for the images. I don't have a lot of experience with apache but I bet there's a way to disable that or (even better) set the modified date for all assets to be the container creation date/time.

**Comment by drasmuss** [comment]
That did the trick, thanks!

I noticed another issue now though, where when I extract a second video it overwrites the frames from the first video (or if I put multiple videos in the `videos_in` folder, they overwrite each other so I only end up with frames from the last video).  Is that the intended behaviour?  I could work around it by just processing one video at a time, I'm just curious if that's a bug or not.

**Comment by jldowns** [comment]
I think that's how it's supposed to work, I've been doing one video at a time too. It's not a good excuse, but I didn't actually write the VATIC code; I just put it in a Docker container. I'm not sure if you've looked through the VATIC documentation at https://github.com/cvondrick/vatic . It has a lot more features than I include in my README (and more than I use in my scripts).

**Comment by drasmuss** [comment]
Sounds good, thanks for your help!
